name: Build and Release ServicoTeste (ARM64)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Mantemos um runner atual, mas rodamos um container compatível

    container:
      image: ubuntu:18.04  # Agora usamos um container com Ubuntu 18.04

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências compatíveis com Jetson Nano
        run: |
          apt update
          apt install -y build-essential gcc-8 g++-8
          apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Compilar para ARM64 (GLIBC 2.27)
        run: |
          export CC=aarch64-linux-gnu-gcc-8
          export CXX=aarch64-linux-gnu-g++-8
          make

      - name: Gerar número da versão
        run: echo "VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Criar Release numerada
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          files: servico_teste
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Criar Release "latest"
        uses: softprops/action-gh-release@v1
        with:
          tag_name: servico_teste-latest
          files: servico_teste
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

