name: Build and Release ServicoTeste (ARM64)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Usa o sistema normal para rodar o checkout

    steps:
      - name: Checkout do código  # Agora o checkout acontece fora do container
        uses: actions/checkout@v3

      - name: Rodar container compatível com a Jetson Nano
        run: |
          docker run --rm -v $(pwd):/src -w /src ubuntu:18.04 /bin/bash -c "
          apt update &&
          apt install -y build-essential gcc-8 g++-8 &&
          apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu &&
          export CC=aarch64-linux-gnu-gcc-8 &&
          export CXX=aarch64-linux-gnu-g++-8 &&
          make
          "

      - name: Gerar número da versão
        run: echo "VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Criar Release numerada
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          files: servico_teste
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Criar Release "latest"
        uses: softprops/action-gh-release@v1
        with:
          tag_name: servico_teste-latest
          files: servico_teste
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

